# Generated by Django 2.2 on 2021-05-14 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(default='', max_length=40)),
                ('a_token', models.CharField(max_length=1000, unique=True)),
                ('r_token', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
